# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c7e4266f443c0b2014fe598047ae2d8afc5beb1ff7bed747ef9659883b4cd241a5374dbb504e0df81ea1801e520161da8b31fefedf85fd1250e6f2e209bbfedb

test:
  secret_key_base: 371c36a7ede12e830fc688a1b4a1f5da4874b789e5df45fb0d0dbde1de6c57268c1aa1b605ce0feb498c6ef4aeb1e92a2785a0b98334e0e036f33a8992d5044b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
